### ISSUE TITLE
Bug: Using `--el` and `--pdf` results in full page pdf generated

### ISSUE THREAD

**Issue by stephanschubert** [vladocar/screenshoteer#8]
I ran:

```bash
screenshoteer --url  https://news.ycombinator.com/item\?id\=18598672 --el ".fatitem" --pdf
```

**Comment by vladocar** [comment]
Thanks! I will fix this in the next version.

**Comment by vladocar** [comment]
I tried but for some reason puppeteer doesn't handle pdf as screenshot.

**Comment by stephanschubert** [comment]
@vladocar Hmm, have you tried [setting the page dimensions and using some custom CSS](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions) to hide the non-selected elements?

> page.pdf() generates a pdf of the page with print css media. To generate a pdf with screen media, call page.emulateMedia('screen') before calling page.pdf():

**Comment by vladocar** [comment]
As you can see from the https://github.com/vladocar/screenshoteer/blob/cafa2455c10963bdc4ad90d828541b9f6e7c67fe/index.js#L76
the pdf is already using  page.emulateMedia('screen'). 

The problem is when const el = await page.$("#main");
el.screenshot(...) works without problem
el.pdf(..) doesn't work.

However I'm sure there is a solution, I simply don't have a time to try everything. 

But you are more then welcome to try. If you find a solution please let me know :)

**Comment by stephanschubert** [comment]
Ah sorry, I didn't check. Understood.. I will let you know if I figure sth out.
